version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ehealth
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./vendor:/var/www/vendor
    networks:
      - app-network

networks:
  app-network:
    driver: bridge