openapi: 3.0.0
info:
  title: eHealth API
  version: 1.0.0
paths:
  /medications:
    post:
      summary: Create a new medication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_id
                - name
                - started_at
                - dosage
                - role
              properties:
                user_id:
                  type: integer
                name:
                  type: string
                started_at:
                  type: string
                  format: date-time
                dosage:
                  type: integer
                note:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: Medication created
  /medications/{id}:
    delete:
      summary: Delete a medication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - role
              properties:
                role:
                  type: string
      responses:
        '204':
          description: Medication deleted
    put:
      summary: Update a medication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - started_at
                - dosage
                - role
              properties:
                name:
                  type: string
                started_at:
                  type: string
                  format: date-time
                dosage:
                  type: integer
                note:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Medication updated
  /medications/{user_id}:
    get:
      summary: Get medications for a user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - role
              properties:
                role:
                  type: string
      responses:
        '200':
          description: Medications retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    started_at:
                      type: string
                      format: date-time
                    dosage:
                      type: integer
                    note:
                      type: string